---
- name: Install Apache HTTP Server and Deploy index.html
  hosts: httpd
  become: true
  tasks:
    - name: Update apt cache (for Debian-based systems)
      apt:
        update_cache: yes
        cache_valid_time: 3600
      when: ansible_os_family == "Debian"

    - name: Install httpd package
      package:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install apache2 package (for Debian-based systems)
      package:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

    - name: Create /var/www/html directory
      file:
        path: /var/www/html
        state: directory
        mode: '0755'
      become: true

    - name: Copy index.html to remote server
      copy:
        src: index.html
        dest: /var/www/html/index.html
        mode: '0644'
      become: true

    - name: Start and enable the httpd service
      service:
        name: httpd
        state: started
        enabled: true
      when: ansible_os_family == "RedHat"

    - name: Start and enable the apache2 service (for Debian-based systems)
      service:
        name: apache2
        state: started
        enabled: true
      when: ansible_os_family == "Debian"
