---
- name: Setup Flask Application
  hosts: aws_ec2
  gather_facts: false

  tasks:
    - name: Update system packages
      become: true
      yum:
        name: '*'
        state: latest
      tags: update

    - name: Install Git
      become: true
      yum:
        name: git
        state: present
      tags: git

    - name: Install Python 3 pip
      become: true
      yum:
        name: python3-pip
        state: present
      tags: python-pip

    - name: Clone repository
      become: true
      git:
        repo: https://github.com/Raz-Dahan/flask-websites.git
        dest: /flask-websites
        force: yes
      tags: git

    - name: Change directory
      become: true
      command: cd /flask-websites/alpaca-flask/
      tags: cd

    - name: Install Python dependencies
      become: true
      pip:
        requirements: /flask-websites/alpaca-flask/requirements.txt
      tags: pip

    - name: Set executable permissions for playbook
      file:
        path: /flask-websites/alpaca-flask/app.py
        mode: ugo+rx
      become: true

    - name: Copy Flask service file
      become: true
      copy:
        content: |
          [Unit]
          Description=Flask Web Application
          After=network.target

          [Service]
          User=root
          WorkingDirectory=/flask-websites/alpaca-flask
          ExecStart=/usr/local/bin/flask run --host=0.0.0.0
          Restart=always

          [Install]
          WantedBy=multi-user.target
        dest: /etc/systemd/system/flask.service
      notify: Restart Flask Service
      tags: service

    - name: Start Flask service
      become: true
      systemd:
        name: flask.service
        state: started
        enabled: yes
      tags: service

  handlers:
    - name: Restart Flask Service
      become: true
      systemd:
        name: flask.service
        state: restarted

    - name: Reload Systemd daemon
      become: true
      shell: systemctl daemon-reload
      changed_when: false
      ignore_errors: true
      tags: service-reload

    - name: Start Flask service (Retry)
      become: true
      systemd:
        name: flask.service
        state: started
        enabled: yes
      tags: service-restart
